version: '3.4'

services:
  catalog.db:
    image: mongo

  basket.db:
    image: redis:alpine

  discount.db:
    image: postgres

  portainer:
    image: portainer/portainer-ce

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  portainer_data:
